"use client";
export default function CGU() {
  return (
    <main className="min-h-screen bg-gray-950 text-white px-4 py-12">
      <div className="max-w-3xl mx-auto">
        <a href="/auth" className="text-blue-400 hover:underline text-sm mb-8 block">← Retour</a>
        <h1 className="text-3xl font-bold text-white mb-2">Conditions Générales d'Utilisation</h1>
        <p className="text-gray-400 mb-2">Version 3 - Juillet 2025</p>
        <p className="text-gray-400 mb-10">Plateforme : Nezro Academy — Responsable : Iurceac Julien</p>
        <div className="flex flex-col gap-8">
          <section><h2 className="text-xl font-bold text-white mb-3">Article 1 - Objet des CGU</h2><p className="text-gray-400 leading-relaxed">Les présentes Conditions Générales d'Utilisation régissent l'accès et l'utilisation de la plateforme privée Nezro Academy. En créant un compte, le membre reconnaît avoir pris connaissance des présentes CGU et les accepter. Elles définissent les règles d'utilisation de Nezro Academy applicables à tout membre de la plateforme.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 2 - Présentation de Nezro Academy</h2><p className="text-gray-400 leading-relaxed">Nezro Academy est une plateforme privée de formation en ligne exploitée par Iurceac Julien (France). Le programme proposé s'intitule Programme YMA. La plateforme est accessible uniquement aux membres dont l'inscription a été validée manuellement par l'administrateur. Aucun paiement n'est effectué directement sur ce site. Toutes les transactions sont réalisées sur la plateforme Beacons.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 3 - Conditions d'accès au service</h2><p className="text-gray-400 leading-relaxed mb-3">L'accès à Nezro Academy est subordonné aux conditions suivantes :</p><ul className="text-gray-400 list-disc pl-6 flex flex-col gap-1"><li>Avoir effectué l'achat du Programme YMA via Beacons et avoir obtenu la validation de son inscription par l'administrateur</li><li>Avoir créé un compte sur la plateforme</li><li>Avoir obtenu la validation de sa demande par l'administrateur</li><li>Avoir accepté les présentes CGU ainsi que la Politique de confidentialité</li></ul><p className="text-gray-400 mt-3">Le site est principalement conçu pour une utilisation sur ordinateur. La compatibilité mobile n'est actuellement pas officiellement garantie.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 4 - Processus d'inscription et validation</h2><ol className="text-gray-400 list-decimal pl-6 flex flex-col gap-1 mb-3"><li>Achat du Programme YMA sur Beacons</li><li>Réception du lien d'accès à Nezro Academy</li><li>Création d'un compte avec prénom, e-mail et mot de passe</li><li>Acceptation obligatoire des CGU et de la Politique de confidentialité</li><li>Soumission de la demande, placée en attente de validation</li><li>Vérification manuelle du paiement par l'administrateur</li><li>Acceptation ou refus de la demande</li></ol><p className="text-gray-400">L'administrateur se réserve le droit de refuser toute demande qui ne satisfait pas aux conditions d'accès. En cas de refus de validation, aucun accès à la plateforme n'est accordé.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 5 - Compte utilisateur et règles d'utilisation</h2><p className="text-gray-400 mb-2">Règles obligatoires :</p><ul className="text-gray-400 list-disc pl-6 flex flex-col gap-1"><li>Un seul compte par personne est autorisé</li><li>Le partage de compte est strictement interdit</li><li>La création de plusieurs comptes est interdite</li><li>Deux connexions simultanées peuvent être autorisées pour un même utilisateur à titre pratique. Elles ne permettent en aucun cas le partage du compte avec un tiers</li><li>Tout contournement de ces règles peut entraîner la suspension du compte</li></ul></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 6 - Sécurité du compte</h2><p className="text-gray-400 leading-relaxed">Le membre est seul responsable de la confidentialité de ses identifiants de connexion (adresse e-mail et mot de passe). Il s'engage à ne pas les divulguer à des tiers et à prendre toutes les précautions nécessaires pour en assurer la sécurité. En cas de compromission de ses identifiants, le membre doit contacter immédiatement l'administrateur à <a href="mailto:cookeddog67@gmail.com" className="text-blue-400 hover:underline">cookeddog67@gmail.com</a>.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 7 - Accès au Programme YMA</h2><p className="text-gray-400 leading-relaxed mb-3">Le Programme YMA est composé de modules incluant des vidéos et des documents. Ces contenus sont exclusivement consultables sur la plateforme Nezro Academy. Le membre dispose d'un accès définitif au Programme YMA conformément aux conditions prévues à l'article 19 des présentes CGU.</p><p className="text-gray-400 mb-2">Sont strictement interdits :</p><ul className="text-gray-400 list-disc pl-6 flex flex-col gap-1"><li>Le téléchargement des vidéos et des PDF</li><li>La copie ou reproduction de tout contenu</li><li>La diffusion ou le partage à des tiers</li><li>La revente ou commercialisation des contenus</li></ul><p className="text-gray-400 mt-3">Les méthodes et connaissances acquises peuvent être librement appliquées dans les projets personnels du membre.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 8 - Propriété intellectuelle</h2><p className="text-gray-400 leading-relaxed">L'ensemble des contenus présents sur Nezro Academy est la propriété exclusive de Iurceac Julien. Toute reproduction, diffusion, revente ou partage non autorisés sont strictement interdits. Les utilisations non autorisées peuvent engager la responsabilité de leur auteur conformément aux dispositions légales applicables.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 9 - Espace membre et fonctionnalités</h2><p className="text-gray-400 mb-2">L'espace membre donne accès aux fonctionnalités suivantes :</p><ul className="text-gray-400 list-disc pl-6 flex flex-col gap-1 mb-3"><li>Programme YMA</li><li>Dashboard</li><li>Annonces</li><li>Membres</li><li>Ressources</li><li>Classement</li><li>Calendrier</li><li>Assistant IA</li><li>Chat privé</li><li>Paramètres</li></ul><p className="text-gray-400 mb-2"><strong className="text-white">Profil :</strong> Chaque membre peut choisir d'afficher uniquement son prénom, ou son prénom et son nom. Les adresses e-mail ne sont jamais visibles par les autres membres.</p><p className="text-gray-400 mb-2"><strong className="text-white">Dashboard :</strong> Chaque membre voit uniquement sa propre progression et ses statistiques. La progression des autres membres n'est jamais visible.</p><p className="text-gray-400 mb-2"><strong className="text-white">Réseaux sociaux :</strong> Peuvent être renseignés dans les paramètres. Ces informations restent strictement privées et ne sont jamais visibles par les autres membres.</p><p className="text-gray-400"><strong className="text-white">Notifications :</strong> Le site utilise uniquement des notifications internes. Aucun e-mail automatique n'est envoyé par Nezro Academy.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 10 - Annonces et interactions</h2><p className="text-gray-400 leading-relaxed">Seul l'administrateur peut publier des annonces. Les membres peuvent lire les annonces, réagir avec des emojis et participer aux sondages. Les membres ne peuvent jamais publier d'annonces eux-mêmes.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 11 - Ressources externes</h2><p className="text-gray-400 leading-relaxed">Certaines ressources redirigent vers des sites externes. Nezro Academy n'est pas responsable du contenu de ces sites. Aucun partenariat ni affiliation n'est en vigueur.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 12 - Assistant IA</h2><p className="text-gray-400 leading-relaxed">L'assistant IA utilise OpenRouter. Les conversations ne sont pas conservées. Une limite d'utilisation est appliquée. Les réponses générées peuvent contenir des erreurs ou être incomplètes et ne constituent en aucun cas une garantie de résultat. Les échanges avec l'assistant IA ne doivent pas contenir d'informations personnelles sensibles ou confidentielles. L'utilisateur reste responsable des informations qu'il choisit de transmettre à l'assistant IA.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 13 - Chat privé</h2><p className="text-gray-400 leading-relaxed">Le chat permet uniquement de communiquer avec l'administrateur. Les membres ne peuvent pas discuter entre eux. Les messages peuvent être supprimés automatiquement après quelques jours.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 14 - Classement et badges</h2><p className="text-gray-400 leading-relaxed">Le classement est visible par tous les membres. Il est basé uniquement sur la progression dans le programme et sert à la motivation. Il ne confère aucun avantage particulier. Les badges sont uniquement décoratifs.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 15 - Responsabilités et absence de garantie</h2><p className="text-gray-400 leading-relaxed">Le Programme YMA fournit des méthodes et ressources à titre pédagogique. Aucun résultat financier, revenu, gain ou performance particulière n'est garanti par Nezro Academy ou le Programme YMA. Les performances dépendent entièrement de l'investissement personnel de chaque membre. Les membres restent seuls responsables de l'utilisation qu'ils font des informations et ressources proposées dans le Programme YMA.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 16 - Suspension et bannissement</h2><p className="text-gray-400 leading-relaxed mb-2">L'administrateur peut suspendre ou supprimer l'accès d'un membre en cas de non-respect des présentes CGU. Selon la gravité des faits, cette mesure peut être appliquée immédiatement. </p><ul className="text-gray-400 list-disc pl-6 mt-2 flex flex-col gap-1"><li>partage de compte ;</li><li>création de plusieurs comptes ;</li><li>copie ou revente de contenus ;</li><li>comportement abusif ;</li><li>tentative de fraude ;</li><li>contournement des mesures de sécurité ;</li><li>perturbation du fonctionnement de la plateforme.</li></ul><p className="text-gray-400 hidden"></p><p className="text-gray-400">Un membre dont l'accès a été suspendu peut contacter l'administrateur à <a href="mailto:cookeddog67@gmail.com" className="text-blue-400 hover:underline">cookeddog67@gmail.com</a>. L'administrateur se réserve le droit de réactiver un compte après examen de la situation.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 17 - Suppression du compte</h2><p className="text-gray-400 leading-relaxed">Le membre peut effectuer la suppression de son compte depuis les Paramètres. Une confirmation est demandée avant suppression définitive. L'accès est immédiatement supprimé. Certaines données peuvent être conservées pour des raisons administratives ou légales, conformément à la Politique de confidentialité de Nezro Academy.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 18 - Évolution de Nezro Academy</h2><p className="text-gray-400 leading-relaxed">Nezro Academy se réserve le droit de faire évoluer la plateforme à tout moment : ajout ou suppression de modules, modification des fonctionnalités, du design, du contenu ou des présentes CGU. Les membres seront informés des changements importants affectant leurs droits ou obligations.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 19 - Durée d'accès au Programme YMA</h2><p className="text-gray-400 leading-relaxed mb-2">Le Programme YMA est proposé avec un accès définitif à la plateforme Nezro Academy après validation de l'inscription par l'administrateur.</p><p className="text-gray-400 leading-relaxed mb-2">Cet accès permet au membre de consulter les contenus disponibles sur la plateforme pendant toute la durée d'exploitation du service, sous réserve du respect des présentes CGU.</p><p className="text-gray-400 leading-relaxed mb-2">L'accès définitif ne constitue pas une garantie de disponibilité permanente de la plateforme en cas d'événement indépendant de la volonté de Nezro Academy, de contrainte technique, légale ou de force majeure.</p><p className="text-gray-400 leading-relaxed">Nezro Academy se réserve la possibilité de faire évoluer, modifier ou remplacer certains contenus du programme afin d'améliorer l'expérience des membres.</p></section>
          <section><h2 className="text-xl font-bold text-white mb-3">Article 20 - Contact</h2><p className="text-gray-400">Pour toute question : <a href="mailto:cookeddog67@gmail.com" className="text-blue-400 hover:underline">cookeddog67@gmail.com</a></p></section>
        </div>
      </div>
    </main>
  );
}
